In [1]:
import os
import sys

import numpy as np

# insert grid2op in the path
print(os.path.abspath("../../.."))
sys.path.insert(0, os.path.abspath("../../.."))

%load_ext autoreload
%autoreload 2

from grid2op.Episode import Episode
%pwd

D:\Projets\Grid2Op


'D:\\Projets\\Grid2Op\\grid2op\\playground\\notebooks'

In [2]:
def attributes(obj):
    elems = [el for el in dir(obj) if not el.startswith("__")]
    methods = [el for el in elems if hasattr(getattr(obj, el), "__call__")]
    attributes = [el for el in elems if el not in methods]
    return dict(attributes=attributes, methods=methods)

In [3]:
indx = 1
path = f"../../../getting_started/study_agent_getting_started/"

episode = Episode.fromdisk(path, indx)

obs = episode.get_observation(0)

act = episode.get_action(0)


Grid2OpException: Grid2OpException "Episode file not found 
 [Errno 2] No such file or directory: 'D:\\Projets\\Grid2Op\\getting_started\\study_agent_getting_started\\1\\_parameters.json'"

In [ ]:
print(attributes(obs))

In [13]:
print(attributes(act))

{'attributes': ['_change_bus_vect', '_dict_inj', '_dim_topo', '_gen_pos_topo_vect', '_gen_to_sub_pos', '_gen_to_subid', '_lines_ex_pos_topo_vect', '_lines_ex_to_sub_pos', '_lines_ex_to_subid', '_lines_impacted', '_lines_or_pos_topo_vect', '_lines_or_to_sub_pos', '_lines_or_to_subid', '_load_pos_topo_vect', '_load_to_sub_pos', '_load_to_subid', '_n_gen', '_n_lines', '_n_load', '_set_line_status', '_set_topo_vect', '_subs_impacted', '_subs_info', '_switch_line_status', 'as_vect', 'authorized_keys', 'vars_action', 'vars_action_set'], 'methods': ['_check_for_ambiguity', '_digest_change_bus', '_digest_change_status', '_digest_hazards', '_digest_injection', '_digest_maintenance', '_digest_set_status', '_digest_setbus', '_ignore_topo_action_if_disconnection', '_obj_caract_from_topo_id', 'as_dict', 'effect_on', 'from_vect', 'get_change_line_status_vect', 'get_set_line_status_vect', 'get_topological_impact', 'reset', 'sample', 'size', 'to_vect', 'update']}


In [15]:
act.effect_on(line_id=0)

{'change_bus_or': False,
 'set_bus_or': 0,
 'change_bus_ex': False,
 'set_bus_ex': 0,
 'set_line_status': 0,
 'change_line_status': False}

In [29]:
obs.state_of(line_id=0)

{'origin': {'p': 108.71890339394342,
  'q': -8.438686230162062,
  'v': 143.1,
  'a': 439.95588997815025,
  'bus': 1,
  'sub_id': 0},
 'extremity': {'p': -106.6750435207041,
  'q': 8.829642045413191,
  'v': 141.07499999999996,
  'a': 438.0611789460228,
  'bus': 1,
  'sub_id': 1}}

In [30]:
obs.line_status

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [19]:
act.effect_on(substation_id=0)

{'change_bus': array([False, False, False]), 'set_bus': array([0, 0, 0])}

In [27]:
act.effect_on(gen_id=-1)

{'new_p': nan,
 'new_v': nan,
 'set_topology': 0.0,
 'change_bus': False,
 'set_bus': 0}

In [17]:
obs.state_of(substation_id=0)

{'topo_vect': array([1, 1, 1]), 'nb_bus': 1}

dict_obs = obs.to_dict()
print(dict_obs)

In [7]:
print(attributes(act))

{'attributes': ['_change_bus_vect', '_dict_inj', '_dim_topo', '_gen_pos_topo_vect', '_gen_to_sub_pos', '_gen_to_subid', '_lines_ex_pos_topo_vect', '_lines_ex_to_sub_pos', '_lines_ex_to_subid', '_lines_impacted', '_lines_or_pos_topo_vect', '_lines_or_to_sub_pos', '_lines_or_to_subid', '_load_pos_topo_vect', '_load_to_sub_pos', '_load_to_subid', '_n_gen', '_n_lines', '_n_load', '_set_line_status', '_set_topo_vect', '_subs_impacted', '_subs_info', '_switch_line_status', 'as_vect', 'authorized_keys', 'vars_action', 'vars_action_set'], 'methods': ['_check_for_ambiguity', '_digest_change_bus', '_digest_change_status', '_digest_hazards', '_digest_injection', '_digest_maintenance', '_digest_set_status', '_digest_setbus', '_ignore_topo_action_if_disconnection', '_obj_caract_from_topo_id', 'as_dict', 'effect_on', 'from_vect', 'get_change_line_status_vect', 'get_set_line_status_vect', 'get_topological_impact', 'reset', 'sample', 'size', 'to_vect', 'update']}


In [8]:
act.vars_action

['load_p', 'load_q', 'prod_p', 'prod_v']

In [9]:
len(obs.timestep_overflow)

20

In [11]:
for attr in attributes(episode)["attributes"]:
    value = getattr(episode, attr)
    if isinstance(value, dict):
        print(f"{attr}:")
        print(value)

meta:
{'backend_type': 'PandaPowerBackend', 'chronics_max_timestep': '575', 'chronics_path': '/home/donnotben/Documents/L2RPN_2ndEdition/chronics_testset_adapted/1', 'cumulative_reward': 8807.13902102747, 'env_type': 'Environment', 'grid_path': '/home/donnotben/Documents/L2RPN_2ndEdition/case14_from_pypownet.json', 'nb_timestep_played': 575}
params:
{'ENV_DC': False, 'FORECAST_DC': False, 'HARD_OVERFLOW_THRESHOLD': 2, 'MAX_LINE_STATUS_CHANGED': 1, 'MAX_SUB_CHANGED': 1, 'NB_TIMESTEP_POWERFLOW_ALLOWED': 2, 'NB_TIMESTEP_RECONNECTION': 10, 'NO_OVERFLOW_DISCONNECTION': False}
times:
{'Agent': {'total': 400.58962535858154}, 'Env': {'apply_act': 4.25318169593811, 'observation_computation': 3.317006826400757, 'powerflow_computation': 6.4346208572387695, 'total': 14.004809379577637}, 'total': 414.73191356658936}


In [12]:
act.effect_on(gen_id=0)

{'new_p': nan,
 'new_v': nan,
 'set_topology': 0.0,
 'change_bus': False,
 'set_bus': 0}

In [13]:
obs.n_lines

20

In [14]:
obs.connectivity_matrix().shape

(56, 56)

In [15]:
obs.bus_connectivity_matrix()

array([[1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.]])

In [16]:
obs.subs_info
# nb objets par poste

array([3, 6, 4, 6, 5, 6, 3, 2, 5, 3, 3, 3, 4, 3])

In [17]:
obs._gen_to_subid

array([1, 2, 5, 7, 0])

In [21]:
obs._load_to_subid

array([ 1,  2, 13,  3,  4,  5,  8,  9, 10, 11, 12])

In [22]:
obs._lines_or_to_subid

array([ 0,  0,  8,  8,  9, 11, 12,  1,  1,  1,  2,  3,  5,  5,  5,  3,  3,
        4,  6,  6])

In [23]:
obs._lines_ex_to_subid

array([ 1,  4,  9, 13, 10, 12, 13,  2,  3,  4,  3,  4, 10, 11, 12,  6,  8,
        5,  7,  8])

In [18]:
obs._gen_to_sub_pos

array([4, 2, 4, 1, 2])

In [25]:
obs._lines_or_to_sub_pos

array([0, 1, 0, 1, 1, 0, 1, 1, 2, 3, 1, 2, 0, 1, 2, 3, 4, 3, 1, 2])

In [19]:
obs._gen_pos_topo_vect

array([ 7, 11, 28, 34,  2])

In [20]:
obs.load_p

array([18.7, 80.6, 41.6,  6.2,  9.8, 26.1,  7.8,  3.2,  5.6, 12.2, 12.8])

In [21]:
obs.topo_vect

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
horizon = episode.observations.shape[0]
load_curve = np.zeros(horizon)
for step in range(horizon):
    load_curve[step] = episode.get_observation(step).load_p[0]

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(load_curve)